export const SETTINGS_LABELS = {
  settings: 'Settings',
  help: 'Help',
  back: 'Back',
  save: 'Save',
  cancel: 'Cancel',
  done: 'Done',

  preference_screen_appearance: 'Appearance',
  preference_screen_appearance_summary: 'Customize the look and feel',
  preference_theme: 'Theme',
  preference_theme_system: 'System default',
  preference_theme_light: 'Light',
  preference_theme_dark: 'Dark',
  preference_screen_colors: 'Color scheme',
  preference_screen_typography: 'Typography',
  preference_screen_shapes: 'Shapes',
  preference_screen_transparencies: 'Transparency',
  theme_import_title: 'Import theme',
  theme_export_title: 'Export theme',
  preference_category_advanced: 'Advanced',
  preference_mdy_color_source: 'Material You color source',
  preference_mdy_color_source_system: 'System colors',
  preference_mdy_color_source_wallpaper: 'Wallpaper colors',

  preference_screen_homescreen: 'Home screen',
  preference_screen_homescreen_summary: 'Clock, search bar, wallpaper, system bars',
  preference_layout_fixed_rotation: 'Fixed portrait orientation',
  preference_layout_fixed_rotation_summary: 'Always show home screen in portrait mode',
  preference_category_widgets: 'Widgets',
  preference_screen_clockwidget: 'Clock',
  preference_screen_clockwidget_summary: 'Configure clock style and components',
  preference_clockwidget_favorites_part: 'Dock',
  preference_clockwidget_favorites_part_summary: 'Show favorite apps below the clock',
  preference_clockwidget_dock_rows: 'Dock rows',
  preference_widgets_on_home_screen: 'Widgets on home screen',
  preference_widgets_on_home_screen_summary: 'Show weather, music and calendar widgets',
  preference_edit_button: 'Edit button',
  preference_widgets_edit_button_summary: 'Show a button to rearrange widgets',
  preference_category_searchbar: 'Search bar',
  preference_search_bar_style: 'Search bar style',
  preference_search_bar_style_summary: 'Choose how the search bar looks',
  preference_search_bar_style_transparent: 'Transparent',
  preference_search_bar_style_solid: 'Solid',
  preference_search_bar_style_hidden: 'Hidden',
  preference_layout_search_bar_position: 'Search bar position',
  search_bar_position_top: 'Top',
  search_bar_position_bottom: 'Bottom',
  preference_layout_fixed_search_bar: 'Fixed search bar',
  preference_layout_fixed_search_bar_summary: 'Keep search bar visible while scrolling',
  preference_category_wallpaper: 'Wallpaper',
  wallpaper: 'Wallpaper',
  preference_wallpaper_summary: 'Change the wallpaper',
  preference_dim_wallpaper: 'Dim wallpaper',
  preference_dim_wallpaper_summary: 'Darken the wallpaper in dark mode',
  preference_blur_wallpaper: 'Blur wallpaper',
  preference_blur_wallpaper_summary: 'Apply a blur effect to the wallpaper',
  preference_blur_wallpaper_unsupported: 'Not supported on this device',
  preference_blur_wallpaper_radius: 'Blur radius',
  preference_category_animations: 'Animations',
  preference_charging_animation: 'Charging animation',
  preference_charging_animation_summary: 'Show an animation while the device is charging',
  preference_category_system_bars: 'System bars',
  preference_status_bar_icons: 'Status bar icons',
  preference_nav_bar_icons: 'Navigation bar icons',
  preference_system_bar_icons_auto: 'Auto',
  preference_system_bar_icons_light: 'Light',
  preference_system_bar_icons_dark: 'Dark',
  preference_hide_status_bar: 'Hide status bar',
  preference_hide_nav_bar: 'Hide navigation bar',

  preference_screen_icons: 'Grid and icons',
  preference_screen_icons_summary: 'Grid size, icons, badges',
  preference_category_grid: 'Grid',
  preference_grid_icon_size: 'Icon size',
  preference_grid_labels: 'Show labels',
  preference_grid_labels_summary: 'Show app names below icons',
  preference_grid_list_style: 'List style',
  preference_grid_list_style_summary: 'Show apps in a vertical list',
  preference_grid_list_icons: 'Show icons in list',
  preference_grid_list_icons_summary: 'Show icons in list view',
  preference_grid_column_count: 'Column count',
  preference_category_icons: 'Icons',
  preference_icon_shape: 'Icon shape',
  preference_enforce_icon_shape: 'Enforce icon shape',
  preference_enforce_icon_shape_summary: 'Apply shape to all icons including adaptive icons',
  preference_themed_icons: 'Themed icons',
  preference_themed_icons_summary: 'Use monochrome icons where available',
  preference_force_themed_icons: 'Force themed icons',
  preference_force_themed_icons_summary: 'Apply theme color to all icons',
  preference_icon_pack: 'Icon pack',
  preference_icon_pack_summary_empty: 'No icon packs installed',
  preference_category_badges: 'Badges',
  preference_notification_badges: 'Notification badges',
  preference_notification_badges_summary: 'Show a badge for pending notifications',
  preference_cloud_badges: 'Cloud badges',
  preference_cloud_badges_summary: 'Show a badge for cloud files',
  preference_suspended_badges: 'Suspended app badges',
  preference_suspended_badges_summary: 'Show a badge for disabled apps',
  preference_shortcut_badges: 'Shortcut badges',
  preference_shortcut_badges_summary: 'Show a badge for app shortcuts',
  preference_plugin_badges: 'Plugin badges',
  preference_plugin_badges_summary: 'Show a badge for plugin results',

  preference_icon_shape_circle: 'Circle',
  preference_icon_shape_square: 'Square',
  preference_icon_shape_rounded_square: 'Rounded square',
  preference_icon_shape_squircle: 'Squircle',
  preference_icon_shape_triangle: 'Triangle',
  preference_icon_shape_pentagon: 'Pentagon',
  preference_icon_shape_hexagon: 'Hexagon',
  preference_icon_shape_teardrop: 'Teardrop',
  preference_icon_shape_pebble: 'Pebble',
  preference_value_system_default: 'System default',

  preference_screen_gestures: 'Gestures',
  preference_screen_gestures_summary: 'Gestures and gesture actions',
  preference_gesture_swipe_down: 'Swipe down',
  preference_gesture_swipe_left: 'Swipe left',
  preference_gesture_swipe_right: 'Swipe right',
  preference_gesture_swipe_up: 'Swipe up',
  preference_gesture_double_tap: 'Double tap',
  preference_gesture_long_press: 'Long press',
  preference_gesture_home_button: 'Home button',

  gesture_action_none: 'None',
  gesture_action_notifications: 'Notifications',
  gesture_action_quick_settings: 'Quick settings',
  gesture_action_lock_screen: 'Lock screen',
  gesture_action_recents: 'Recents',
  gesture_action_power_menu: 'Power menu',
  gesture_action_open_search: 'Search',
  gesture_action_widgets: 'Widgets',
  gesture_action_feed: 'Feed',
  gesture_action_launch_app: 'Launch app',

  missing_permission_accessibility_gesture_settings: 'This action requires accessibility permission',

  preference_screen_search: 'Search',
  preference_screen_search_summary: 'Search, tags, excluded results',
  preference_search_favorites: 'Favorites',
  preference_search_favorites_summary: 'Show favorite and frequently used apps',
  preference_search_apps: 'Apps',
  preference_search_apps_summary: 'Search installed apps',
  preference_search_files: 'Files',
  preference_search_files_summary: 'Search local and cloud files',
  preference_search_contacts: 'Contacts',
  preference_search_contacts_summary: 'Search contacts',
  preference_search_calendar: 'Calendar',
  preference_search_calendar_summary: 'Search calendar events',
  preference_search_appshortcuts: 'App shortcuts',
  preference_search_appshortcuts_summary: 'Search app shortcuts',
  preference_search_calculator: 'Calculator',
  preference_search_calculator_summary: 'Calculate math expressions',
  preference_search_unitconverter: 'Unit converter',
  preference_search_unitconverter_summary: 'Convert units and currencies',
  preference_search_wikipedia: 'Wikipedia',
  preference_search_wikipedia_summary: 'Search Wikipedia articles',
  preference_search_websites: 'Websites',
  preference_search_websites_summary: 'Search websites',
  preference_search_locations: 'Places',
  preference_search_locations_summary: 'Search nearby places',
  preference_screen_search_actions: 'Quick actions',
  preference_search_search_actions_summary: 'Configure quick actions bar',
  preference_hidden_items: 'Hidden items',
  preference_hidden_items_summary: 'Manage hidden apps and items',
  preference_screen_tags: 'Tags',
  preference_screen_tags_summary: 'Manage tags and tagged items',
  preference_default_filter: 'Default filter',
  preference_default_filter_summary: 'Set default search filter',
  preference_filter_bar: 'Filter bar',
  preference_filter_bar_summary: 'Show filter bar above keyboard',
  preference_customize_filter_bar: 'Customize filter bar',
  preference_customize_filter_bar_summary: 'Choose which filters to show',
  preference_search_bar_auto_focus: 'Auto-focus keyboard',
  preference_search_bar_auto_focus_summary: 'Open keyboard when search bar is tapped',
  preference_search_bar_launch_on_enter: 'Launch on enter',
  preference_search_bar_launch_on_enter_summary: 'Launch first result on enter key',
  preference_layout_search_results: 'Search results order',
  search_results_order_top_down: 'Top-down',
  search_results_order_bottom_up: 'Bottom-up',

  preference_screen_integrations: 'Integrations',
  preference_screen_integrations_summary: 'Manage connected accounts and services',
  preference_screen_plugins: 'Plugins',
  preference_screen_plugins_summary: 'Manage installed extensions',

  preference_screen_locale: 'Language and region',
  preference_screen_locale_summary: 'Language, units, time format',
  preference_time_format: 'Time format',
  preference_time_format_system: 'System default',
  preference_time_format_12h: '12-hour',
  preference_time_format_24h: '24-hour',
  preference_measurement_system: 'Measurement system',
  preference_measurement_system_metric: 'Metric',
  preference_measurement_system_uk: 'United Kingdom',
  preference_measurement_system_us: 'United States',

  preference_screen_backup: 'Backup and restore',
  preference_screen_backup_summary: 'Export and import launcher data',
  preference_screen_debug: 'Debug',
  preference_screen_debug_summary: 'Troubleshooting tools',

  preference_screen_about: 'About',
  preference_screen_about_summary: 'App and license information',
  preference_screen_buildinfo: 'Build information',
  preference_screen_buildinfo_summary: 'More information about this build',

  missing_permission_notification_badges: 'Notification access required',
  missing_permission_contact_search_settings: 'Contacts permission required',
  missing_permission_calendar_search_settings: 'Calendar permission required',
  missing_permission_appshortcuts_search_settings: 'App shortcuts permission required',
  missing_permission_location_search: 'Location permission required',
};

export const GESTURE_ACTIONS = [
  { label: SETTINGS_LABELS.gesture_action_none, value: 'NoAction' as const },
  { label: SETTINGS_LABELS.gesture_action_notifications, value: 'Notifications' as const },
  { label: SETTINGS_LABELS.gesture_action_quick_settings, value: 'QuickSettings' as const },
  { label: SETTINGS_LABELS.gesture_action_lock_screen, value: 'ScreenLock' as const },
  { label: SETTINGS_LABELS.gesture_action_recents, value: 'Recents' as const },
  { label: SETTINGS_LABELS.gesture_action_power_menu, value: 'PowerMenu' as const },
  { label: SETTINGS_LABELS.gesture_action_open_search, value: 'Search' as const },
  { label: SETTINGS_LABELS.gesture_action_widgets, value: 'Widgets' as const },
  { label: SETTINGS_LABELS.gesture_action_launch_app, value: 'Launch' as const },
];

export const ICON_SHAPES = [
  { label: SETTINGS_LABELS.preference_value_system_default, value: 'PlatformDefault' as const },
  { label: SETTINGS_LABELS.preference_icon_shape_circle, value: 'Circle' as const },
  { label: SETTINGS_LABELS.preference_icon_shape_square, value: 'Square' as const },
  { label: SETTINGS_LABELS.preference_icon_shape_rounded_square, value: 'RoundedSquare' as const },
  { label: SETTINGS_LABELS.preference_icon_shape_squircle, value: 'Squircle' as const },
  { label: SETTINGS_LABELS.preference_icon_shape_triangle, value: 'Triangle' as const },
  { label: SETTINGS_LABELS.preference_icon_shape_pentagon, value: 'Pentagon' as const },
  { label: SETTINGS_LABELS.preference_icon_shape_hexagon, value: 'Hexagon' as const },
  { label: SETTINGS_LABELS.preference_icon_shape_teardrop, value: 'Teardrop' as const },
  { label: SETTINGS_LABELS.preference_icon_shape_pebble, value: 'Pebble' as const },
];

export const THEME_OPTIONS = [
  { label: SETTINGS_LABELS.preference_theme_system, value: 'System' as const },
  { label: SETTINGS_LABELS.preference_theme_light, value: 'Light' as const },
  { label: SETTINGS_LABELS.preference_theme_dark, value: 'Dark' as const },
];

export const SYSTEM_BAR_COLOR_OPTIONS = [
  { label: SETTINGS_LABELS.preference_system_bar_icons_auto, value: 'Auto' as const },
  { label: SETTINGS_LABELS.preference_system_bar_icons_light, value: 'Light' as const },
  { label: SETTINGS_LABELS.preference_system_bar_icons_dark, value: 'Dark' as const },
];

export const SEARCH_BAR_POSITION_OPTIONS = [
  { label: SETTINGS_LABELS.search_bar_position_top, value: false as const },
  { label: SETTINGS_LABELS.search_bar_position_bottom, value: true as const },
];

export const SEARCH_RESULTS_ORDER_OPTIONS = [
  { label: SETTINGS_LABELS.search_results_order_top_down, value: false as const },
  { label: SETTINGS_LABELS.search_results_order_bottom_up, value: true as const },
];

export const TIME_FORMAT_OPTIONS = [
  { label: SETTINGS_LABELS.preference_time_format_system, value: 'System' as const },
  { label: SETTINGS_LABELS.preference_time_format_12h, value: 'TwelveHour' as const },
  { label: SETTINGS_LABELS.preference_time_format_24h, value: 'TwentyFourHour' as const },
];

export const MEASUREMENT_SYSTEM_OPTIONS = [
  { label: SETTINGS_LABELS.preference_measurement_system_metric, value: 'Metric' as const },
  { label: SETTINGS_LABELS.preference_measurement_system_uk, value: 'UnitedKingdom' as const },
  { label: SETTINGS_LABELS.preference_measurement_system_us, value: 'UnitedStates' as const },
  { label: SETTINGS_LABELS.preference_value_system_default, value: 'System' as const },
];
