import { text, integer, sqliteTable } from 'drizzle-orm/sqlite-core';

export const colors = sqliteTable('colors', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),

  corePaletteA1: integer('core_palette_a1'),
  corePaletteA2: integer('core_palette_a2'),
  corePaletteA3: integer('core_palette_a3'),
  corePaletteN1: integer('core_palette_n1'),
  corePaletteN2: integer('core_palette_n2'),
  corePaletteE: integer('core_palette_e'),

  lightPrimary: text('light_primary'),
  lightOnPrimary: text('light_on_primary'),
  lightPrimaryContainer: text('light_primary_container'),
  lightOnPrimaryContainer: text('light_on_primary_container'),
  lightSecondary: text('light_secondary'),
  lightOnSecondary: text('light_on_secondary'),
  lightSecondaryContainer: text('light_secondary_container'),
  lightOnSecondaryContainer: text('light_on_secondary_container'),
  lightTertiary: text('light_tertiary'),
  lightOnTertiary: text('light_on_tertiary'),
  lightTertiaryContainer: text('light_tertiary_container'),
  lightOnTertiaryContainer: text('light_on_tertiary_container'),
  lightError: text('light_error'),
  lightOnError: text('light_on_error'),
  lightErrorContainer: text('light_error_container'),
  lightOnErrorContainer: text('light_on_error_container'),
  lightSurface: text('light_surface'),
  lightOnSurface: text('light_on_surface'),
  lightOnSurfaceVariant: text('light_on_surface_variant'),
  lightOutline: text('light_outline'),
  lightOutlineVariant: text('light_outline_variant'),
  lightInverseSurface: text('light_inverse_surface'),
  lightInverseOnSurface: text('light_inverse_on_surface'),
  lightInversePrimary: text('light_inverse_primary'),
  lightSurfaceDim: text('light_surface_dim'),
  lightSurfaceBright: text('light_surface_bright'),
  lightSurfaceContainerLowest: text('light_surface_container_lowest'),
  lightSurfaceContainerLow: text('light_surface_container_low'),
  lightSurfaceContainer: text('light_surface_container'),
  lightSurfaceContainerHigh: text('light_surface_container_high'),
  lightSurfaceContainerHighest: text('light_surface_container_highest'),
  lightBackground: text('light_background'),
  lightOnBackground: text('light_on_background'),
  lightSurfaceTint: text('light_surface_tint'),
  lightScrim: text('light_scrim'),
  lightSurfaceVariant: text('light_surface_variant'),

  darkPrimary: text('dark_primary'),
  darkOnPrimary: text('dark_on_primary'),
  darkPrimaryContainer: text('dark_primary_container'),
  darkOnPrimaryContainer: text('dark_on_primary_container'),
  darkSecondary: text('dark_secondary'),
  darkOnSecondary: text('dark_on_secondary'),
  darkSecondaryContainer: text('dark_secondary_container'),
  darkOnSecondaryContainer: text('dark_on_secondary_container'),
  darkTertiary: text('dark_tertiary'),
  darkOnTertiary: text('dark_on_tertiary'),
  darkTertiaryContainer: text('dark_tertiary_container'),
  darkOnTertiaryContainer: text('dark_on_tertiary_container'),
  darkError: text('dark_error'),
  darkOnError: text('dark_on_error'),
  darkErrorContainer: text('dark_error_container'),
  darkOnErrorContainer: text('dark_on_error_container'),
  darkSurface: text('dark_surface'),
  darkOnSurface: text('dark_on_surface'),
  darkOnSurfaceVariant: text('dark_on_surface_variant'),
  darkOutline: text('dark_outline'),
  darkOutlineVariant: text('dark_outline_variant'),
  darkInverseSurface: text('dark_inverse_surface'),
  darkInverseOnSurface: text('dark_inverse_on_surface'),
  darkInversePrimary: text('dark_inverse_primary'),
  darkSurfaceDim: text('dark_surface_dim'),
  darkSurfaceBright: text('dark_surface_bright'),
  darkSurfaceContainerLowest: text('dark_surface_container_lowest'),
  darkSurfaceContainerLow: text('dark_surface_container_low'),
  darkSurfaceContainer: text('dark_surface_container'),
  darkSurfaceContainerHigh: text('dark_surface_container_high'),
  darkSurfaceContainerHighest: text('dark_surface_container_highest'),
  darkBackground: text('dark_background'),
  darkOnBackground: text('dark_on_background'),
  darkSurfaceTint: text('dark_surface_tint'),
  darkScrim: text('dark_scrim'),
  darkSurfaceVariant: text('dark_surface_variant'),
});

export type Color = typeof colors.$inferSelect;
export type NewColor = typeof colors.$inferInsert;
